### ISSUE TITLE
Find() method ObfuscatesIds not overriding

### ISSUE THREAD

**Issue by sanderbongers** [molovo/laravel-model-traits#1]
The find() method in the ObfuscatesIds trait is not overriding the default Laravel find() method (anymore?). So when a model is retrieved, it looks for the obfuscated id and doesn't decode it first.

I know this class you wrote is 3 years old, they might have changed something. But I cannot get it work, do you have any idea how to make it work again?

**Comment by molovo** [comment]
I'll be honest, I have no idea any more. I haven't used Laravel properly for quite a few years

**Comment by sanderbongers** [comment]
Alright, thanks for responding so quickly anyways!
